// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Ball_8cae42249e7d26c4689af19fe55bd2f9Index = 0;
		public const int Cube_6205896415a6a2640b6e4489bce936a2Index = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Ball_8cae42249e7d26c4689af19fe55bd2f9", 0 },

			{ "Cube_6205896415a6a2640b6e4489bce936a2", 1 },

		};
	}
}
